# Generated by Django 3.2.25 on 2024-09-18 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='busroute_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from1', models.CharField(max_length=100)),
                ('to', models.CharField(max_length=100)),
                ('busnum', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='notification_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('notification', models.CharField(max_length=1000)),
                ('date', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='student_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('photo', models.FileField(upload_to='')),
                ('admissions', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('balance', models.BigIntegerField()),
                ('status', models.CharField(max_length=100)),
                ('BUSROUTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.busroute_table')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='stop_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('fee', models.IntegerField()),
                ('BUSROUTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.busroute_table')),
            ],
        ),
        migrations.CreateModel(
            name='payment_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('amount', models.BigIntegerField()),
                ('BUSSSTAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.busroute_table')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='location_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('BUSSSTAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.busroute_table')),
            ],
        ),
        migrations.CreateModel(
            name='complaint_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('complaint', models.CharField(max_length=1000)),
                ('reply', models.CharField(max_length=100)),
                ('BUSSSTAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.busroute_table')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='bussstaff_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('proof', models.FileField(upload_to='')),
                ('BUSROUTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.busroute_table')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='busnotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('notification', models.CharField(max_length=1000)),
                ('BUSSSTAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.busroute_table')),
            ],
        ),
        migrations.CreateModel(
            name='attendence_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('attendence', models.IntegerField()),
                ('BUSSSTAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.busroute_table')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table')),
            ],
        ),
    ]
