# Generated by Django 5.1.1 on 2025-01-15 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_bussstaff_busnotification_bussroutenumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='notistatus_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOTIFICATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.notification_table')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table')),
            ],
        ),
    ]
