# Generated by Django 5.1.1 on 2025-01-16 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_request_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_table',
            name='STUDENT',
        ),
        migrations.AddField(
            model_name='request_table',
            name='ATTENDANCE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.attendence_table'),
            preserve_default=False,
        ),
    ]
