# Generated by Django 5.1.1 on 2025-01-21 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_request_table_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='busnotistatus_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOTIFICATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.busnotification')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table')),
            ],
        ),
    ]
